version: '3.1'

services:

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "4301:8080"

  web:
    build: ./
    restart: always
    ports:
      - "4302:8080"
